apiVersion: v1
kind: Service
metadata:
  name: {{ include "echo-hostname.fullname" . }}
  labels:
    {{- include "echo-hostname.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.trafficDistribution }}
  trafficDistribution: {{ .Values.service.trafficDistribution }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "echo-hostname.selectorLabels" . | nindent 4 }}
